services:
  traefik:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/auth`) || PathPrefix(`/me`)"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.services.user-service.loadbalancer.server.port=8000"
    env_file:
      - services/user-service/.env

  cart-service:
    build:
      context: .
      dockerfile: services/cart-service/Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cart-service.rule=PathPrefix(`/cart`)"
      - "traefik.http.routers.cart-service.entrypoints=web"
      - "traefik.http.services.cart-service.loadbalancer.server.port=8000"
    env_file:
      - services/cart-service/.env

  storage-service:
    build:
      context: .
      dockerfile: services/storage-service/Dockerfile
    expose:
      - "50051"
    env_file:
      - services/storage-service/.env
