# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pb.storage import storage_pb2 as storage_dot_storage__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in storage/storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/storage.StorageService/UploadFile',
                request_serializer=storage_dot_storage__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=storage_dot_storage__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.GeneratePresignedUrl = channel.unary_unary(
                '/storage.StorageService/GeneratePresignedUrl',
                request_serializer=storage_dot_storage__pb2.GeneratePresignedUrlRequest.SerializeToString,
                response_deserializer=storage_dot_storage__pb2.GeneratePresignedUrlResponse.FromString,
                _registered_method=True)
        self.UpdateFile = channel.unary_unary(
                '/storage.StorageService/UpdateFile',
                request_serializer=storage_dot_storage__pb2.UpdateFileRequest.SerializeToString,
                response_deserializer=storage_dot_storage__pb2.UpdateFileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/storage.StorageService/DeleteFile',
                request_serializer=storage_dot_storage__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=storage_dot_storage__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/storage.StorageService/ListFiles',
                request_serializer=storage_dot_storage__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=storage_dot_storage__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePresignedUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=storage_dot_storage__pb2.UploadFileRequest.FromString,
                    response_serializer=storage_dot_storage__pb2.UploadFileResponse.SerializeToString,
            ),
            'GeneratePresignedUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePresignedUrl,
                    request_deserializer=storage_dot_storage__pb2.GeneratePresignedUrlRequest.FromString,
                    response_serializer=storage_dot_storage__pb2.GeneratePresignedUrlResponse.SerializeToString,
            ),
            'UpdateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFile,
                    request_deserializer=storage_dot_storage__pb2.UpdateFileRequest.FromString,
                    response_serializer=storage_dot_storage__pb2.UpdateFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=storage_dot_storage__pb2.DeleteFileRequest.FromString,
                    response_serializer=storage_dot_storage__pb2.DeleteFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=storage_dot_storage__pb2.ListFilesRequest.FromString,
                    response_serializer=storage_dot_storage__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/UploadFile',
            storage_dot_storage__pb2.UploadFileRequest.SerializeToString,
            storage_dot_storage__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePresignedUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/GeneratePresignedUrl',
            storage_dot_storage__pb2.GeneratePresignedUrlRequest.SerializeToString,
            storage_dot_storage__pb2.GeneratePresignedUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/UpdateFile',
            storage_dot_storage__pb2.UpdateFileRequest.SerializeToString,
            storage_dot_storage__pb2.UpdateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteFile',
            storage_dot_storage__pb2.DeleteFileRequest.SerializeToString,
            storage_dot_storage__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ListFiles',
            storage_dot_storage__pb2.ListFilesRequest.SerializeToString,
            storage_dot_storage__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
